void l_pro(const int &iClientSock);
void p_pro(const int &iClientSock);
void f_pro(const int &iClientSock);
void s_pro(const int &iClientSock);
void r_pro(const int &iClientSock);
void b_pro(const int &iClientSock);
void a_pro(const int &iClientSock);
void c_pro(const int &iClientSock);
void e_pro(const int &iClientSock);